[package]
name = "rusty_neuron"
version = "0.0.0"
edition = "2021"

[[bin]]
name = "xor"
path = "examples/xor.rs"

[dependencies]
clap = "4.5.9"
enum_dispatch = "0.3.13"
nalgebra = { version = "0.33.0", features = ["rand"] }
image = "0.25.2"

[profile.release]
debug = true
