[package]
name = "rusty_grad"
version = "0.0.0"
edition = "2021"

[lib]
name = "rusty_grad"
src = "src/lib.rs"

[dependencies]
enum_dispatch = "0.3.13"
nalgebra = { version = "0.33.0", features = ["rand"] }
image = "0.25.2"
clap = "4.5.9"

[build-dependencies]
cc = "1.1.6"
